FILE(GLOB OPDE_SCENEMANAGER_SOURCES ${OPDE_SOURCE_DIR}/src/scenemanager/*.h)
FILE(GLOB OPDE_SCENEMANAGER_HEADERS ${OPDE_SOURCE_DIR}/src/scenemanager/*.cpp)
SET(OPDE_SCENEMANAGER_FILES ${OPDE_SCENEMANAGER_HEADERS} ${OPDE_SCENEMANAGER_SOURCES})
