FILE(GLOB OPDE_BINDING_SOURCES ${OPDE_SOURCE_DIR}/src/bindings/*.h)
FILE(GLOB OPDE_BINDING_HEADERS ${OPDE_SOURCE_DIR}/src/bindings/*.cpp)
SET(OPDE_BINDING_FILES ${OPDE_BINDING_HEADERS} ${OPDE_BINDING_SOURCES})
